type Query{
    fetch_checkin_configs: CheckinConfigResponse
}

type Mutation{
    update_checkin_configs(newconfig: String): Response
}


type Response{
    success: Boolean
    msg: String
}

type CheckInConfig{
    scan_prev_hours: Int
    scan_next_hours: Int
    password: String
}

type CheckinConfigResponse{
    success: Boolean!
    msg: String
    config: CheckInConfig
}