
type Query {
    fetch_apprentice_courses: SuccessAndApprenticeCourseResult
    fetch_apprentice_course_info(id:Int!): SuccessAndCouseInfoResult
}

type SuccessAndCouseInfoResult {
    success: Boolean
    msg: String
    course: ApprenticeCourse
}

type SuccessAndApprenticeCourseResult{

    success: Boolean
    msg: String
    courses: [ApprenticeCourse]
}

type ApprenticeCourse {
    id: Int
    name: String
}

type Mutation{
    create_apprentice_course(name:String!): SuccessResult
    update_apprentice_course(name:String!, id: Int!): SuccessResult
}